# Abstract algorithm type and associated functions

"""
    AbstractAlgorithm

Abstract type for GCP algorithms.

Concrete types `ConcreteAlgorithm <: AbstractAlgorithm` should implement
`_gcp!(rng, M, X, loss, constraints, algorithm::ConcreteAlgorithm)`
that modifies the initialization `M` and returns the modified version.
"""
abstract type AbstractAlgorithm end

"""
    _gcp!(rng, M, X, loss, constraints, algorithm)

Internal function to compute an approximate rank-`r` CP decomposition
of the data tensor `X` with respect to the loss function `loss` and the
constraints `constraints` using the algorithm `algorithm` with random
numbers generated by `rng`, modifying the initialization `M` and
returning the modified version.
"""
function _gcp! end
